### ISSUE TITLE
[Usage]: Ready to be used?

### ISSUE THREAD

**Issue by fzyzcjy** [IsaacRe/vllm-kvcompress#7]
### Your current environment

Hi thanks for the lib! I wonder whether this is ready to be used, or just highly experimental and is not ready?

### How would you like to use vllm

I want to run inference of a [specific model](put link here). I don't know how to integrate it with vllm.

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by IsaacRe** [comment]
Hi, this is still somewhat experimental but is functional within the constraints outlined in the readme. If you encounter any bugs please create an issue and I'll do my best to resolve it quickly!

**Comment by fzyzcjy** [comment]
Thank you!
